version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=/api
    ports:
      - "3000:80"  # Nginx serves on port 80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://carboncube_ke_db_owner:npg_X6KBHbn8IWaO@ep-noisy-wind-a2hin9x9-pooler.eu-central-1.aws.neon.tech/carboncube_ke_db?sslmode=require
      - RAILS_ENV=development
      - CLOUDINARY_API_KEY=787352969935943
      - CLOUDINARY_API_SECRET=oamnYHBDZa8nRcVKpFlrnFqBXIc
      - RAILS_MASTER_KEY=c07efe8bcc61269190eb1fd1210858d0
    command: ["sh", "-c", "rm -f /app/tmp/pids/server.pid && rails server -b 0.0.0.0 -p 3001"]
