version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=https://carboncube-ke.com/api
      - REACT_APP_SITE_URL=https://carboncube-ke.com
      - REACT_APP_WEBSOCKET_URL=wss://carboncube-ke.com/cable
    restart: unless-stopped
