// Sample Email Draft for Seller 114 (Victor Kirui - SasaTech Africa)
// This demonstrates the targeted email features with real seller data

const sampleEmailDraft = {
	subject: "Complete Your Seller Profile for Better Visibility",

	// This would be generated by the email template system
	html: `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Complete Your Seller Profile for Better Visibility</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f4f4f4;
        }
        .email-container {
            background-color: #ffffff;
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        .header {
            background: linear-gradient(135deg, #1f2937 0%, #374151 100%);
            color: white;
            padding: 30px 20px;
            text-align: center;
        }
        .logo {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .content {
            padding: 30px 20px;
        }
        .greeting {
            font-size: 18px;
            margin-bottom: 20px;
            color: #1f2937;
        }
        .highlight-box {
            background-color: #f3f4f6;
            border-left: 4px solid #3b82f6;
            padding: 20px;
            margin: 20px 0;
            border-radius: 5px;
        }
        .highlight-box h3 {
            margin-top: 0;
            color: #1f2937;
        }
        .message {
            font-size: 16px;
            line-height: 1.8;
            margin-bottom: 25px;
        }
        .cta-button {
            display: inline-block;
            background: linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%);
            color: white;
            padding: 12px 30px;
            text-decoration: none;
            border-radius: 25px;
            font-weight: bold;
            margin: 20px 10px;
            transition: transform 0.2s;
        }
        .cta-button:hover {
            transform: translateY(-2px);
        }
        .cta-button.secondary {
            background: linear-gradient(135deg, #10b981 0%, #059669 100%);
        }
        .footer {
            background-color: #f9fafb;
            padding: 20px;
            text-align: center;
            border-top: 1px solid #e5e7eb;
            color: #6b7280;
            font-size: 14px;
        }
        .social-links {
            margin: 15px 0;
        }
        .social-links a {
            color: #3b82f6;
            text-decoration: none;
            margin: 0 10px;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <div class="header">
            <div class="logo">CARBONCUBE</div>
            <p>Your Marketplace Partner</p>
        </div>
        
        <div class="content">
            <div class="greeting">Dear Victor Kirui,</div>
            
            <!-- Personalized Seller Info -->
            <div class="highlight-box">
                <h3>📊 Your SasaTech Africa Performance</h3>
                <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-top: 15px;">
                    <div>
                        <strong>🏪 Shop:</strong> SasaTech Africa<br>
                        <strong>📍 Location:</strong> Kirichwa Shelters<br>
                        <strong>📧 Email:</strong> victorquaint@gmail.com
                    </div>
                    <div>
                        <strong>📦 Total Ads:</strong> 17<br>
                        <strong>⭐ Reviews:</strong> 16 (Avg: 3.94)<br>
                        <strong>🏷️ Category:</strong> No Category
                    </div>
                </div>
            </div>
            
            <div class="message">
                We're excited to see the growing traction on our platform! To help you get the most out of your listings and improve your visibility to potential buyers, we encourage you to:<br><br>
                
                ✅ Complete your seller profile with accurate details<br>
                ✅ Add a professional profile picture<br>
                ✅ Verify your contact information<br>
                ✅ Update your business description<br><br>
                
                Complete profiles receive 40% more engagement from buyers. Take a few minutes to update your details and watch your sales grow!
            </div>
            
            <div style="text-align: center;">
                <a href="https://carboncube.com/seller/dashboard" class="cta-button">
                    Update My Profile
                </a>
                <a href="https://carboncube.com/seller/114" class="cta-button secondary">
                    View My Shop
                </a>
            </div>
        </div>
        
        <div class="footer">
            <p>Best regards,<br><strong>The Carbon Team</strong></p>
            <div class="social-links">
                <a href="#">Website</a> | <a href="#">Support</a> | <a href="#">Help Center</a>
            </div>
            <p>© 2024 Carbon Cube. All rights reserved.</p>
        </div>
    </div>
</body>
</html>`,
};

export default sampleEmailDraft;
