name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up SSH and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 188.245.245.79
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/root/CARBON/frontend
            git pull origin main
            npm install
            npm run build
            sudo systemctl restart nginx


